export enum Rank {
    ADM = "Admral",
    LTADM = "Lieutenant ADMIRAL",
    VADM  = "Vice Admiral",
    RADM =  "Rear Admiral Upper Half", 
    RDML = "Rear Admiral Lower Half",
    CAPT = "Captain",
    CDR = "Commander",
    LTCDR = "Lieutenant Commander",
    LT = "Lieutenant",
    LTJG = "Lieutenant Junior Grade",
    ENS = "Ensign",
    MCPON = "Master Cheif Petty Officer Of The Navy",
    MCPO = "Master Cheif Petty Officer",
    SCPO = "Senior Cheif Petty Offcier",
    CPO = "Cheif Petty Offcier",
    PO1 = "Petty Officer 1",
    PO2 = "Petty Officer 2",
    PO3 = "Petty Officer 3",
}